apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-exporter-config
  labels:
    app: domain-exporter
data:
  domains.yaml: |-
    domains:
      - google.com
      - google.co.uk

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: domain-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain-exporter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: domain-exporter
    spec:
      containers:
      - name: domain-exporter
        image: quay.io/shift/domain_exporter
        ports:
          - containerPort: 9203
        args: [
          "--config=/etc/domain-exporter/domains.yaml",
          "--bind=:9203",
          "--log.level=info",
        ]
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /etc/domain-exporter
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: domain-exporter-config

---

apiVersion: v1
kind: Service
metadata:
  name: domain-exporter
  annotations:
    prometheus.io/port: "9203"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - port: 9203
    targetPort: 9203
    protocol: TCP
    name: domain-exporter
  selector:
    app: domain-exporter
