# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: domain_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
      - ''
    ldflags: -s -w -X github.com/prometheus/common/version.Version={{ .Version }}
        -X github.com/prometheus/common/version.Revision={{ .Commit }}
        -X github.com/prometheus/common/version.Branch={{ .Env.TRAVIS_BRANCH }}
        -X github.com/prometheus/common/version.BuildUser={{ .Env.TRAVIS_REPO_SLUG }}
        -X github.com/prometheus/common/version.BuildDate={{ .Date }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  format_overrides:
    - goos: windows
      format: zip
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  -
    goos: linux
    goarch: amd64
    binary: domain_exporter
    image: quay.io/shift/domain_exporter
    dockerfile: Dockerfile
    tag_templates:
    - "{{ .Tag }}"
    - "v{{ .Major }}"
    - latest
  -
    goos: linux
    goarch: arm
    goarm: ''
    binary: domain_exporter
    image: quay.io/shift/domain_exporter
    dockerfile: Dockerfile
    tag_templates:
    - "{{ .Tag }}-arm"
    - "v{{ .Major }}-arm"
    - latest-arm
  -
    goos: linux
    goarch: arm64
    goarm: ''
    binary: domain_exporter
    image: quay.io/shift/domain_exporter
    dockerfile: Dockerfile
    tag_templates:
    - "{{ .Tag }}-arm64"
    - "v{{ .Major }}-arm64"
    - latest-arm64
