apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "domain-exporter.fullname" . }}
  labels:
    {{- include "domain-exporter.labels" . | nindent 4 }}
data:
  domains.yaml: |-
    domains:
      {{- toYaml .Values.domains | nindent 6 }}
